services:
  dws-secure-shell:
    build: .
    container_name: dws-secure-shell
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5050:5050"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Vancouver
    # This configures git to trust the folder, pulls the code, then runs the app
    command: /bin/sh -c "git config --global --add safe.directory /app && git pull && python app.py"
